version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    command: ./config
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - hosts

  postgres:
    image: 'postgres:latest'
    container_name: postgres
    volumes:
      - "./migrate/up/*.up.sql:/docker-entrypoint-initdb.d/"

    networks:
      - hosts
    environment:
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432

networks:
  hosts:
    driver: "bridge"