version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:14.5-alpine
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgrespw
    ports:
      - 5432:5432